title: Little Wonder Paper Co.
description: High-quality printables, digital art, and paper goods.
url: "https://www.littlewonderpaperco.works"

# This enables the SEO plugin
plugins:
  - jekyll-seo-tag
